name: Build & Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ← ここでビルドが必要なら追加する（方法 B）

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .          # 重要！ _site ではなく現在のディレクトリを指定

      - uses: actions/deploy-pages@v4
        id: deployment

